# Generated by Django 5.0.6 on 2024-05-18 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee_isdelete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='l_name',
            new_name='l_date',
        ),
    ]
